@startuml

package "Sistema de Aluguel de Carros" {

    [Interface Web] --> [Gerenciador de Pedidos e Contratos]
    [Interface Web] --> [Autenticação]
    
    [Gerenciador de Pedidos e Contratos] --> [Gerenciador de Veículos]
    [Gerenciador de Pedidos e Contratos] --> [Repositórios de Dados]

    [Autenticação] --> [Repositórios de Dados]
    [Gerenciador de Veículos] --> [Repositórios de Dados]
    [Repositórios de Dados] --> [Banco de Dados]

}

@enduml
